### ISSUE TITLE
Add JSON-LD context

### ISSUE THREAD

**Issue by jceb** [decentralized-identity/linked-vp#12]
The `LinkedVerifiablePresentations` endpoint is an extension to the DID core specification and should therefore provide a JSON-LD context for the new type.

**Comment by peacekeeper** [comment]
I know we talked about this just yesterday, but today I had some new thoughts on this:
1. I agree with [@brianorwhatever 's comment](https://github.com/decentralized-identity/linked-vp/pull/28#discussion_r1445064480) that it should be singular. The "type" property should simply indicate the type of the service, and it doesn't make a difference whether there are one or many.
2. Here is another funny (maybe radical) thought. I think the "Linked" part is unnecessary. I know that "LinkedVerifiablePresentations" is modeled after "LinkedDomains", but that doesn't mean we have to follow that pattern. I also know the name of this work item is "Linked Verifiable Presentations". I'm not suggesting we change that. But think about the following: If you link to something, and the link has a type, do you then really need to say it's a "Linked"VerifiablePresentation? For other services, would you have to explicitly say you have a "Linked"DIDComm or a "Linked"DecentralizedWebNode service? Isn't the whole point of service endpoints, and URLs, and JSON-LD, and linked data, that resources and services can ALWAYS be "linked"? So I think this doesn't have to be explicitly expressed in the "type" value. So my proposal would be to just use the service type "VerifiablePresentation" instead of "LinkedVerifiablePresentation". You might now say, but "VerifiablePresentation" [is already defined elsewhere](https://www.w3.org/TR/vc-data-model/#presentations-0) so we can't overload it. But hey, we would be re-using that instead of overloading it. And doesn't this align super nicely, that the type of the service endpoint in the DID document directly matches the type of the document it points to? Isn't this maybe an essential pattern of how DIDs, URLs, and linked data should work "naturally"? Please share your thoughts :)

**Comment by jceb** [comment]
Very interesting thoughts. I like the proposal.

My 2 cents:
- Technically speaking, with this change we gain the option of leaving the serviceEndpoint property empty and define the presentation right in the DID Document 🤯
- There are no mandatory properties that we have to add to the service section because of the VerifiablePresentation type 👍 https://w3c.github.io/vc-data-model/#presentations-0
- This would also give us the relatedResource property for free, since it's part of the VP context 🎉 
- This change has some potential to confuse people, however we'd gain immediate machine level understanding of what the service endpoint is referring to 🤩

@brianorwhatever what do you think?

**Comment by jceb** [comment]
Whoops, I didn't want to merge the context PR and close this issue. However, the other PR included this PR 🤦

**Comment by jceb** [comment]
We concluded in the work item call on 2024-02-08 that the separate context and the name will stay in place. The only change will do is to use the singular name for the context; `LinkedVerifiablePresentation`.
